apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod-cka
spec:
  tolerations:
    - key: "node-role.kubernetes.io/control-plane"
      operator: "Exists"
      effect: "NoSchedule"
  containers:
    - name: my-container
      image: nginx:latest
      volumeMounts:
        - mountPath: /var/www/html
          name: nginx-storage
  volumes:
    - name: nginx-storage
      persistentVolumeClaim:
        claimName: nginx-pvc-cka
